# https://taskfile.dev

version: '3'

dotenv: ['.env']

vars:
  SERVICE: goalkeepr

tasks:
  default:
    desc: Display available tasks
    cmds:
      - task --list
    silent: true

  # ==================================================================================== #
  # DEVELOPMENT
  # ==================================================================================== #

  run:
    desc: Run the application with Reflex for auto-reload
    aliases: [dev]
    cmds:
      - echo 'Starting app with Reflex auto-reload...'
      - reflex -s -r '\.(go|html|css|js)$' -- go run ./cmd/app -env=dev -database-driver=sqlite -database-dsn={{.DB_DSN}}

  sqlc:
    desc: Generate source code from SQL
    aliases: [generate]
    cmds:
      - sqlc generate

  tw:
    desc: Run Tailwind CSS in watch mode
    cmds:
      - tailwindcss -i ./ui/static/css/index.css -o ./ui/static/dist/index.css --watch

  sec:
    desc: gosec analyzes Go source code to look for common programming mistakes that can lead to security problems.
    aliases: [scan]
    cmds:
      - gosec -exclude-dir=internal/database/gen ./...
      - govulncheck ./...

  dev:
    cmds:
      - task --parallel tw run

  # ==================================================================================== #
  # QUALITY CONTROL
  # ==================================================================================== #

  audit:
    desc: Format, vet and test all code
    cmds:
      - echo 'Formatting code...'
      - go fmt ./...
      - echo 'Vetting code...'
      - go vet ./...
      - echo 'Running tests...'
      - go test -race -vet=off ./...

  vendor:
    desc: Tidy and vendor dependencies
    cmds:
      - echo 'Tidying and verifying module dependencies...'
      - go mod tidy
      - go mod verify
      - echo 'Vendoring dependencies...'
      - GOWORK=off go mod vendor

  cover:
    desc: Run test coverage
    cmds:
      - echo 'Test coverage...'
      - go test -covermode=count -coverprofile=/tmp/profile.out ./...

  analyze:
    desc: Analyze the test coverage in your browser
    deps: [cover]
    cmds:
      - echo 'Analyze test coverage...'
      - go tool cover -html=/tmp/profile.out

  # ==================================================================================== #
  # BUILD
  # ==================================================================================== #

  build:
    desc: Build the service for Linux AMD64
    aliases: [build/linux_amd64]
    deps: [audit]
    cmds:
      - echo 'Building cmd/{{.SERVICE}}...'
      - go build -ldflags='-s' -o=./bin/{{.SERVICE}} ./cmd/app
      - task: build:linux

  build:linux:
    internal: true
    cmds:
      - |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build --tags extended -ldflags='-s' \
          -o=./bin/linux_amd64/{{.SERVICE}} ./cmd/app

  # ==================================================================================== #
  # PRODUCTION
  # ==================================================================================== #

  prod:connect:
    desc: Connect to the production server
    cmds:
      - ssh setup@{{.PRODUCTION_HOST_IP}}

  prod:deploy:
    desc: Deploy goalkeepr to production
    vars:
      REMOTE_USER: setup
    cmds:
      - rsync -P ./bin/linux_amd64/{{.SERVICE}} {{.REMOTE_USER}}@{{.PRODUCTION_HOST_IP}}:~
      - rsync -P ./remote/production/{{.SERVICE}}.service {{.REMOTE_USER}}@{{.PRODUCTION_HOST_IP}}:~
      - |
        ssh -t {{.REMOTE_USER}}@{{.PRODUCTION_HOST_IP}} \
          'sudo mv ~/{{.SERVICE}}.service /etc/systemd/system/ && \
           sudo systemctl enable {{.SERVICE}} && \
           sudo systemctl restart {{.SERVICE}}'
