// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: share.sql

package share

import (
	"context"
	"database/sql"
)

const countByUserID = `-- name: CountByUserID :one
SELECT COUNT(*) FROM share WHERE user_id = ?
`

func (q *Queries) CountByUserID(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const create = `-- name: Create :execresult
INSERT INTO share (user_id, public_id)
VALUES (?, ?)
`

type CreateParams struct {
	UserID   int64
	PublicID string
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, create, arg.UserID, arg.PublicID)
}

const delete = `-- name: Delete :execresult
DELETE FROM share WHERE id = ?
`

func (q *Queries) Delete(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, delete, id)
}

const getAll = `-- name: GetAll :many
SELECT id, user_id, public_id
FROM share
WHERE user_id = ?
`

func (q *Queries) GetAll(ctx context.Context, userID int64) ([]Share, error) {
	rows, err := q.db.QueryContext(ctx, getAll, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Share
	for rows.Next() {
		var i Share
		if err := rows.Scan(&i.ID, &i.UserID, &i.PublicID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserIDByPublicID = `-- name: GetUserIDByPublicID :one
SELECT user_id FROM share WHERE public_id = ?
`

func (q *Queries) GetUserIDByPublicID(ctx context.Context, publicID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserIDByPublicID, publicID)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}
