// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: goals.sql

package goals

import (
	"context"
	"database/sql"
)

const create = `-- name: Create :one
INSERT INTO goals (user_id, goal, description, due, visible_to_public, achieved)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, user_id, goal, due, visible_to_public, achieved, description
`

type CreateParams struct {
	UserID          int64
	Goal            sql.NullString
	Description     sql.NullString
	Due             sql.NullInt64
	VisibleToPublic sql.NullInt64
	Achieved        sql.NullInt64
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.UserID,
		arg.Goal,
		arg.Description,
		arg.Due,
		arg.VisibleToPublic,
		arg.Achieved,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Goal,
		&i.Due,
		&i.VisibleToPublic,
		&i.Achieved,
		&i.Description,
	)
	return i, err
}

const delete = `-- name: Delete :execresult
DELETE FROM goals
WHERE id = ? AND user_id = ?
`

type DeleteParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) Delete(ctx context.Context, arg DeleteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, delete, arg.ID, arg.UserID)
}

const get = `-- name: Get :one
SELECT id, user_id, goal, due, visible_to_public, achieved, description FROM goals
WHERE id = ? AND user_id = ?
`

type GetParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) Get(ctx context.Context, arg GetParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, get, arg.ID, arg.UserID)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Goal,
		&i.Due,
		&i.VisibleToPublic,
		&i.Achieved,
		&i.Description,
	)
	return i, err
}

const getAll = `-- name: GetAll :many
SELECT id, user_id, goal, due, visible_to_public, achieved, description FROM goals
WHERE user_id = ?
ORDER BY due ASC
`

func (q *Queries) GetAll(ctx context.Context, userID int64) ([]Goal, error) {
	rows, err := q.db.QueryContext(ctx, getAll, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Goal
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Goal,
			&i.Due,
			&i.VisibleToPublic,
			&i.Achieved,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllShared = `-- name: GetAllShared :many
SELECT id, user_id, goal, due, visible_to_public, achieved, description FROM goals
WHERE user_id = ? AND visible_to_public = 1
ORDER BY due ASC
`

func (q *Queries) GetAllShared(ctx context.Context, userID int64) ([]Goal, error) {
	rows, err := q.db.QueryContext(ctx, getAllShared, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Goal
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Goal,
			&i.Due,
			&i.VisibleToPublic,
			&i.Achieved,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const update = `-- name: Update :execresult
UPDATE goals
SET goal = ?, description = ?, due = ?, visible_to_public = ?, achieved = ?
WHERE id = ? AND user_id = ?
`

type UpdateParams struct {
	Goal            sql.NullString
	Description     sql.NullString
	Due             sql.NullInt64
	VisibleToPublic sql.NullInt64
	Achieved        sql.NullInt64
	ID              int64
	UserID          int64
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, update,
		arg.Goal,
		arg.Description,
		arg.Due,
		arg.VisibleToPublic,
		arg.Achieved,
		arg.ID,
		arg.UserID,
	)
}
