// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package goals

import (
	"database/sql"
)

type Goal struct {
	ID              int64
	UserID          int64
	Goal            sql.NullString
	Due             sql.NullInt64
	VisibleToPublic sql.NullInt64
	Achieved        sql.NullInt64
}
