// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package success_criteria

import (
	"database/sql"
)

type SuccessCriterium struct {
	ID          int64
	GoalID      int64
	UserID      int64
	Description string
	Completed   sql.NullInt64
	Position    sql.NullInt64
	CreatedAt   int64
}
