// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: success_criteria.sql

package success_criteria

import (
	"context"
	"database/sql"
)

const createSuccessCriteria = `-- name: CreateSuccessCriteria :one
INSERT INTO success_criteria (goal_id, user_id, description, completed, position, created_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, goal_id, user_id, description, completed, position, created_at
`

type CreateSuccessCriteriaParams struct {
	GoalID      int64
	UserID      int64
	Description string
	Completed   sql.NullInt64
	Position    sql.NullInt64
	CreatedAt   int64
}

func (q *Queries) CreateSuccessCriteria(ctx context.Context, arg CreateSuccessCriteriaParams) (SuccessCriterium, error) {
	row := q.db.QueryRowContext(ctx, createSuccessCriteria,
		arg.GoalID,
		arg.UserID,
		arg.Description,
		arg.Completed,
		arg.Position,
		arg.CreatedAt,
	)
	var i SuccessCriterium
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.UserID,
		&i.Description,
		&i.Completed,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllSuccessCriteriaByGoal = `-- name: DeleteAllSuccessCriteriaByGoal :execresult
DELETE FROM success_criteria
WHERE goal_id = ? AND user_id = ?
`

type DeleteAllSuccessCriteriaByGoalParams struct {
	GoalID int64
	UserID int64
}

func (q *Queries) DeleteAllSuccessCriteriaByGoal(ctx context.Context, arg DeleteAllSuccessCriteriaByGoalParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteAllSuccessCriteriaByGoal, arg.GoalID, arg.UserID)
}

const deleteSuccessCriteria = `-- name: DeleteSuccessCriteria :execresult
DELETE FROM success_criteria
WHERE id = ? AND user_id = ?
`

type DeleteSuccessCriteriaParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteSuccessCriteria(ctx context.Context, arg DeleteSuccessCriteriaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteSuccessCriteria, arg.ID, arg.UserID)
}

const getAllSuccessCriteriaByGoal = `-- name: GetAllSuccessCriteriaByGoal :many
SELECT id, goal_id, user_id, description, completed, position, created_at FROM success_criteria
WHERE goal_id = ? AND user_id = ?
ORDER BY position ASC, created_at ASC
`

type GetAllSuccessCriteriaByGoalParams struct {
	GoalID int64
	UserID int64
}

func (q *Queries) GetAllSuccessCriteriaByGoal(ctx context.Context, arg GetAllSuccessCriteriaByGoalParams) ([]SuccessCriterium, error) {
	rows, err := q.db.QueryContext(ctx, getAllSuccessCriteriaByGoal, arg.GoalID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuccessCriterium
	for rows.Next() {
		var i SuccessCriterium
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.UserID,
			&i.Description,
			&i.Completed,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSuccessCriteria = `-- name: GetSuccessCriteria :one
SELECT id, goal_id, user_id, description, completed, position, created_at FROM success_criteria
WHERE id = ? AND user_id = ?
`

type GetSuccessCriteriaParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetSuccessCriteria(ctx context.Context, arg GetSuccessCriteriaParams) (SuccessCriterium, error) {
	row := q.db.QueryRowContext(ctx, getSuccessCriteria, arg.ID, arg.UserID)
	var i SuccessCriterium
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.UserID,
		&i.Description,
		&i.Completed,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const toggleSuccessCriteriaCompleted = `-- name: ToggleSuccessCriteriaCompleted :execresult
UPDATE success_criteria
SET completed = CASE WHEN completed = 0 THEN 1 ELSE 0 END
WHERE id = ? AND user_id = ?
`

type ToggleSuccessCriteriaCompletedParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) ToggleSuccessCriteriaCompleted(ctx context.Context, arg ToggleSuccessCriteriaCompletedParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, toggleSuccessCriteriaCompleted, arg.ID, arg.UserID)
}

const updateSuccessCriteria = `-- name: UpdateSuccessCriteria :execresult
UPDATE success_criteria
SET description = ?, completed = ?, position = ?
WHERE id = ? AND user_id = ?
`

type UpdateSuccessCriteriaParams struct {
	Description string
	Completed   sql.NullInt64
	Position    sql.NullInt64
	ID          int64
	UserID      int64
}

func (q *Queries) UpdateSuccessCriteria(ctx context.Context, arg UpdateSuccessCriteriaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateSuccessCriteria,
		arg.Description,
		arg.Completed,
		arg.Position,
		arg.ID,
		arg.UserID,
	)
}
