// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: branding.sql

package branding

import (
	"context"
	"database/sql"
)

const createOrUpdate = `-- name: CreateOrUpdate :execresult
INSERT INTO branding (user_id, title, description)
VALUES (?, ?, ?)
ON CONFLICT(user_id) DO UPDATE SET
    title = excluded.title,
    description = excluded.description
`

type CreateOrUpdateParams struct {
	UserID      int64
	Title       sql.NullString
	Description sql.NullString
}

func (q *Queries) CreateOrUpdate(ctx context.Context, arg CreateOrUpdateParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOrUpdate, arg.UserID, arg.Title, arg.Description)
}

const delete = `-- name: Delete :execresult
DELETE FROM branding
WHERE user_id = ?
`

func (q *Queries) Delete(ctx context.Context, userID int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, delete, userID)
}

const getByUserID = `-- name: GetByUserID :one
SELECT id, user_id, title, description
FROM branding
WHERE user_id = ?
`

func (q *Queries) GetByUserID(ctx context.Context, userID int64) (Branding, error) {
	row := q.db.QueryRowContext(ctx, getByUserID, userID)
	var i Branding
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
	)
	return i, err
}
