// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package branding

import (
	"database/sql"
)

type Branding struct {
	ID          int64
	UserID      int64
	Title       sql.NullString
	Description sql.NullString
}
