// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package users

import (
	"database/sql"
)

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	LockedUntil  sql.NullInt64
	CreatedAt    int64
	UpdatedAt    int64
}
