// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package users

import (
	"context"
	"database/sql"
)

const create = `-- name: Create :execresult
INSERT INTO users (email, password_hash, created_at, updated_at)
VALUES (?, ?, unixepoch(), unixepoch())
`

type CreateParams struct {
	Email        string
	PasswordHash string
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, create, arg.Email, arg.PasswordHash)
}

const delete = `-- name: Delete :execresult
DELETE FROM users
WHERE id = ?
`

func (q *Queries) Delete(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, delete, id)
}

const getByEmail = `-- name: GetByEmail :one
SELECT id, email, password_hash, locked_until, created_at, updated_at
FROM users
WHERE email = ?
`

func (q *Queries) GetByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getByID = `-- name: GetByID :one
SELECT id, email, password_hash, locked_until, created_at, updated_at
FROM users
WHERE id = ?
`

func (q *Queries) GetByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
